"""Temperature Table

Revision ID: 8eb0368d4037
Revises: 
Create Date: 2018-04-08 16:52:22.162528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eb0368d4037'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reg_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reg_temp_temp'), 'reg_temp', ['temp'], unique=True)
    op.create_index(op.f('ix_reg_temp_timestamp'), 'reg_temp', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reg_temp_timestamp'), table_name='reg_temp')
    op.drop_index(op.f('ix_reg_temp_temp'), table_name='reg_temp')
    op.drop_table('reg_temp')
    # ### end Alembic commands ###
