"""users table

Revision ID: 0011ba4a6f10
Revises: 
Create Date: 2018-04-07 17:25:25.913005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0011ba4a6f10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reg_temp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temp', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reg_temp_temp'), 'reg_temp', ['temp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reg_temp_temp'), table_name='reg_temp')
    op.drop_table('reg_temp')
    # ### end Alembic commands ###
